# Auto-generated by Idyllium compiler
import sys

def __idyl_write(*args):
    for arg in args:
        sys.stdout.write(str(arg))
    sys.stdout.flush()

def __idyl_get_string():
    return sys.stdin.readline().rstrip('\n')

def __idyl_get_int():
    try:
        return int(sys.stdin.readline().rstrip('\n'))
    except ValueError:
        print("Ошибка: ожидалось целое число", file=sys.stderr)
        sys.exit(1)

def __idyl_get_float():
    try:
        return float(sys.stdin.readline().rstrip('\n'))
    except ValueError:
        print("Ошибка: ожидалось дробное число", file=sys.stderr)
        sys.exit(1)


def main():
    name = __idyl_get_string()
    age = __idyl_get_int()
    height = __idyl_get_float()
    __idyl_write('Привет, ', name, '! Вам ', age, ' лет и ', height, ' м.\n')


if __name__ == "__main__":
    main()