#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const rootDir = path.resolve(__dirname, '..');
const distDir = path.join(rootDir, 'dist');
const sourceWebDir = path.join(rootDir, 'packages', 'web-ide');
const outputWebDir = path.join(distDir, 'web');
const outputAssetsDir = path.join(outputWebDir, 'assets');
const sourceWebAssetsDir = path.join(sourceWebDir, 'assets');
const sourceFontsDir = path.join(sourceWebDir, 'fonts');
const outputFontsDir = path.join(outputWebDir, 'fonts');
const monacoSourceDir = path.join(rootDir, 'node_modules', 'monaco-editor', 'min', 'vs');
const monacoOutputDir = path.join(outputWebDir, 'monaco', 'vs');
const rendererSourceDir = path.join(rootDir, 'packages', 'gui-renderer');
const rendererOutputDir = path.join(outputWebDir, 'gui-renderer');
const papaParseSource = path.join(rootDir, 'node_modules', 'papaparse', 'papaparse.min.js');
const markedSource = path.join(rootDir, 'node_modules', 'marked', 'lib', 'marked.umd.js');
const domPurifySource = path.join(rootDir, 'node_modules', 'dompurify', 'dist', 'purify.min.js');
const vendorOutputDir = path.join(outputWebDir, 'vendor');
const browserEntry = path.join(distDir, 'src', 'browser.js');
const sqlJsWasmSource = path.join(rootDir, 'node_modules', 'sql.js', 'dist', 'sql-wasm-browser.wasm');

if (!fs.existsSync(browserEntry)) {
  console.error('Browser entry was not found. Run npm run build first.');
  process.exit(1);
}

fs.rmSync(outputWebDir, { recursive: true, force: true });
fs.mkdirSync(outputAssetsDir, { recursive: true });

for (const item of ['index.html', 'app.css', 'app.js']) {
  fs.copyFileSync(path.join(sourceWebDir, item), path.join(outputWebDir, item));
}
if (fs.existsSync(sourceFontsDir)) {
  fs.cpSync(sourceFontsDir, outputFontsDir, { recursive: true });
}
if (fs.existsSync(sourceWebAssetsDir)) {
  fs.cpSync(sourceWebAssetsDir, outputAssetsDir, { recursive: true });
}
if (!fs.existsSync(monacoSourceDir)) {
  console.error('Monaco editor was not found. Run npm install first.');
  process.exit(1);
}
fs.cpSync(monacoSourceDir, monacoOutputDir, { recursive: true });

fs.cpSync(rendererSourceDir, rendererOutputDir, { recursive: true });
if (!fs.existsSync(papaParseSource)) {
  console.error('Papa Parse was not found. Run npm install first.');
  process.exit(1);
}
if (!fs.existsSync(markedSource) || !fs.existsSync(domPurifySource)) {
  console.error('Markdown preview dependencies were not found. Run npm install first.');
  process.exit(1);
}
fs.mkdirSync(vendorOutputDir, { recursive: true });
fs.copyFileSync(papaParseSource, path.join(vendorOutputDir, 'papaparse.min.js'));
fs.copyFileSync(markedSource, path.join(vendorOutputDir, 'marked.umd.js'));
fs.copyFileSync(domPurifySource, path.join(vendorOutputDir, 'purify.min.js'));
if (!fs.existsSync(sqlJsWasmSource)) {
  console.error('sql.js WASM was not found. Run npm install first.');
  process.exit(1);
}
fs.copyFileSync(sqlJsWasmSource, path.join(outputAssetsDir, 'sql-wasm-browser.wasm'));
fs.writeFileSync(path.join(outputWebDir, 'gui-preview.html'), guiPreviewHtml(), 'utf8');
const bundledCore = browserBundle(browserEntry);
validateBrowserBundle(bundledCore);
fs.writeFileSync(path.join(outputAssetsDir, 'idyllium-web-core.js'), bundledCore, 'utf8');

console.log(`Idyllium Web IDE built at ${path.relative(rootDir, outputWebDir)}`);

function browserBundle(entryFile) {
  const collected = collectModules(entryFile);
  const modules = collected.modules;
  const entries = [...modules.entries()].sort(([left], [right]) => left.localeCompare(right));
  const moduleFactories = entries.map(([id, file]) => moduleFactory(id, file));
  const resolutions = Object.fromEntries([...collected.resolutions.entries()].sort(([left], [right]) => left.localeCompare(right)));
  const entryId = moduleId(entryFile);

  return `/* Generated by tools/build-web-ide.js */
(function (global) {
  'use strict';

  var modules = {
${moduleFactories.join(',\n')}
  };
  var cache = {};
  var builtins = createBuiltins();
  var resolutions = ${JSON.stringify(resolutions)};

  function load(id) {
    if (cache[id]) return cache[id].exports;
    if (!modules[id]) throw new Error('Module was not bundled: ' + id);
    var module = { exports: {} };
    cache[id] = module;
    modules[id](makeRequire(id), module, module.exports);
    return module.exports;
  }

  function makeRequire(from) {
    return function require(request) {
      if (builtins[request]) return builtins[request];
      var resolved = resolutions[from + '\u0000' + request];
      if (resolved) return load(resolved);
      if (request.charAt(0) !== '.') throw new Error('Unsupported browser require: ' + request + ' from ' + from);
      return load(resolveModuleId(from, request));
    };
  }

  function resolveModuleId(from, request) {
    var base = from.slice(0, from.lastIndexOf('/') + 1);
    var id = normalizePath(base + request);
    if (!/\\.js$/u.test(id)) id += '.js';
    return id;
  }

  function normalizePath(value) {
    var parts = value.replace(/\\\\/gu, '/').split('/');
    var result = [];
    for (var i = 0; i < parts.length; i++) {
      var part = parts[i];
      if (!part || part === '.') continue;
      if (part === '..') result.pop();
      else result.push(part);
    }
    return result.join('/');
  }

  function createBuiltins() {
    var pathBuiltin = {
      basename: function basename(value, ext) {
        var name = pathBuiltin.normalize(value).split('/').pop() || '';
        return ext && name.endsWith(ext) ? name.slice(0, -ext.length) : name;
      },
      dirname: function dirname(value) {
        var normalized = pathBuiltin.normalize(value);
        if (normalized === '/') return '/';
        var index = normalized.lastIndexOf('/');
        if (index <= 0) return normalized.charAt(0) === '/' ? '/' : '.';
        return normalized.slice(0, index);
      },
      isAbsolute: function isAbsolute(value) {
        return String(value).charAt(0) === '/';
      },
      join: function join() {
        return pathBuiltin.normalize(Array.prototype.join.call(arguments, '/'));
      },
      normalize: function normalize(value) {
        var raw = String(value).replace(/\\\\/gu, '/');
        var absolute = raw.charAt(0) === '/';
        var parts = raw.split('/');
        var result = [];
        for (var i = 0; i < parts.length; i++) {
          var part = parts[i];
          if (!part || part === '.') continue;
          if (part === '..') result.pop();
          else result.push(part);
        }
        return (absolute ? '/' : '') + result.join('/');
      },
      resolve: function resolve() {
        var value = '';
        for (var i = 0; i < arguments.length; i++) {
          var part = String(arguments[i]);
          value = part.charAt(0) === '/' ? part : value + '/' + part;
        }
        return pathBuiltin.normalize(value || '/');
      }
    };

    var fsBuiltin = {
      appendFileSync: function appendFileSync() { throw new Error('Node fs is not available in the browser'); },
      existsSync: function existsSync() { return false; },
      readFileSync: function readFileSync() { throw new Error('Node fs is not available in the browser'); },
      statSync: function statSync() { throw new Error('Node fs is not available in the browser'); },
      writeFileSync: function writeFileSync() { throw new Error('Node fs is not available in the browser'); }
    };

    return {
      buffer: { Buffer: BrowserBuffer },
      fs: fsBuiltin,
      path: pathBuiltin
    };
  }

  function BrowserBuffer(length) {
    return new Uint8Array(length);
  }

  BrowserBuffer.alloc = function alloc(length) {
    return enhanceBuffer(new Uint8Array(length));
  };

  BrowserBuffer.from = function from(value, encoding) {
    if (typeof value === 'string') {
      return enhanceBuffer(new TextEncoder().encode(value));
    }
    return enhanceBuffer(new Uint8Array(value));
  };

  function enhanceBuffer(bytes) {
    bytes.toString = function toString(encoding) {
      if (!encoding || String(encoding).toLowerCase() === 'utf8' || String(encoding).toLowerCase() === 'utf-8') {
        return new TextDecoder('utf-8').decode(bytes);
      }
      throw new Error('Unsupported browser buffer encoding: ' + encoding);
    };
    bytes.writeFloatBE = function writeFloatBE(value, offset) {
      new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength).setFloat32(offset, value, false);
    };
    bytes.writeDoubleBE = function writeDoubleBE(value, offset) {
      new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength).setFloat64(offset, value, false);
    };
    bytes.readFloatBE = function readFloatBE(offset) {
      return new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength).getFloat32(offset, false);
    };
    bytes.readDoubleBE = function readDoubleBE(offset) {
      return new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength).getFloat64(offset, false);
    };
    return bytes;
  }

  global.process = global.process || { cwd: function cwd() { return '/workspace'; } };
  global.Idyllium = load(${JSON.stringify(entryId)});
}(typeof window !== 'undefined' ? window : globalThis));
`;
}

function collectModules(entryFile) {
  const modules = new Map();
  const resolutions = new Map();
  const visit = (file) => {
    const id = moduleId(file);
    if (modules.has(id)) return;
    modules.set(id, file);

    if (path.extname(file) === '.json') return;
    const source = fs.readFileSync(file, 'utf8');
    for (const request of requireRequests(source)) {
      if (isBrowserBuiltin(request)) continue;
      const resolved = resolveRequire(file, request);
      resolutions.set(`${id}\0${request}`, moduleId(resolved));
      visit(resolved);
    }
  };
  visit(entryFile);
  return { modules, resolutions };
}

function moduleFactory(id, file) {
  if (path.extname(file) === '.json') {
    const value = JSON.parse(fs.readFileSync(file, 'utf8'));
    return `${JSON.stringify(id)}: function(require, module, exports) { module.exports = ${JSON.stringify(value)}; }`;
  }
  const amdIsolation = id === 'node_modules/tslib/tslib.js' ? 'var define;\n' : '';
  return `${JSON.stringify(id)}: function(require, module, exports) {\n${amdIsolation}${fs.readFileSync(file, 'utf8')}\n}`;
}

function validateBrowserBundle(source) {
  const amdDefine = function define() {};
  amdDefine.amd = {};
  const context = {
    ArrayBuffer,
    DataView,
    TextDecoder,
    TextEncoder,
    Uint8Array,
    URL,
    clearTimeout,
    console,
    define: amdDefine,
    setTimeout,
  };
  context.window = context;
  context.globalThis = context;
  vm.runInNewContext(source, context, {
    filename: 'idyllium-web-core.js',
    timeout: 10000,
  });
  if (!context.Idyllium || typeof context.Idyllium.prepareIdylliumBrowserProgram !== 'function') {
    throw new Error('Generated browser core did not expose prepareIdylliumBrowserProgram');
  }
}

function requireRequests(source) {
  const result = [];
  const pattern = /require\(["']([^"']+)["']\)/gu;
  let match = pattern.exec(source);
  while (match) {
    result.push(match[1]);
    match = pattern.exec(source);
  }
  return result;
}

function resolveRequire(fromFile, request) {
  const candidate = request === 'fontkit'
    ? path.join(path.dirname(require.resolve('fontkit', { paths: [rootDir] })), 'browser.cjs')
    : request.startsWith('.')
    ? path.resolve(path.dirname(fromFile), request)
    : require.resolve(request, { paths: [path.dirname(fromFile), rootDir] });
  const files = [
    candidate,
    `${candidate}.js`,
    path.join(candidate, 'index.js'),
  ];
  for (const file of files) {
    if (fs.existsSync(file) && fs.statSync(file).isFile()) return file;
  }
  throw new Error(`Cannot resolve ${request} from ${fromFile}`);
}

function moduleId(file) {
  return path.relative(rootDir, file).split(path.sep).join('/');
}

function isBrowserBuiltin(request) {
  return request === 'buffer' || request === 'fs' || request === 'path';
}

function guiPreviewHtml() {
  const guiRenderer = require(path.join(rendererSourceDir, 'index.js'));
  return guiRenderer.renderGuiWebviewHtml({
    cssUri: 'gui-renderer/renderer.css',
    hostBootstrap: "window.IdylliumGuiHost = { postMessage: function(message) { parent.postMessage({ type: 'idylliumGuiEvent', message: message }, '*'); } };",
    nonce: 'idyllium-web',
    scriptUri: 'gui-renderer/renderer.js',
    state: { windows: [], canvases: [], modals: [], output: '' },
  });
}
