#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');
const distDir = path.join(rootDir, 'dist');
const sourceWebDir = path.join(rootDir, 'packages', 'web-ide');
const outputWebDir = path.join(distDir, 'web');
const outputAssetsDir = path.join(outputWebDir, 'assets');
const outputDocsDir = path.join(outputWebDir, 'docs');
const sourceWebAssetsDir = path.join(sourceWebDir, 'assets');
const sourceFontsDir = path.join(sourceWebDir, 'fonts');
const outputFontsDir = path.join(outputWebDir, 'fonts');
const monacoSourceDir = path.join(rootDir, 'node_modules', 'monaco-editor', 'min', 'vs');
const monacoOutputDir = path.join(outputWebDir, 'monaco', 'vs');
const rendererSourceDir = path.join(rootDir, 'packages', 'gui-renderer');
const rendererOutputDir = path.join(outputWebDir, 'gui-renderer');
const browserEntry = path.join(distDir, 'src', 'browser.js');
const lessonSpecDir = path.join(rootDir, 'spec', 'lessons');

if (!fs.existsSync(browserEntry)) {
  console.error('Browser entry was not found. Run npm run build first.');
  process.exit(1);
}

fs.rmSync(outputWebDir, { recursive: true, force: true });
fs.mkdirSync(outputAssetsDir, { recursive: true });
fs.mkdirSync(outputDocsDir, { recursive: true });

for (const item of ['index.html', 'app.css', 'app.js']) {
  fs.copyFileSync(path.join(sourceWebDir, item), path.join(outputWebDir, item));
}
if (fs.existsSync(sourceFontsDir)) {
  fs.cpSync(sourceFontsDir, outputFontsDir, { recursive: true });
}
if (fs.existsSync(sourceWebAssetsDir)) {
  fs.cpSync(sourceWebAssetsDir, outputAssetsDir, { recursive: true });
}
if (!fs.existsSync(monacoSourceDir)) {
  console.error('Monaco editor was not found. Run npm install first.');
  process.exit(1);
}
fs.cpSync(monacoSourceDir, monacoOutputDir, { recursive: true });

fs.cpSync(rendererSourceDir, rendererOutputDir, { recursive: true });
fs.writeFileSync(path.join(outputWebDir, 'gui-preview.html'), guiPreviewHtml(), 'utf8');
fs.writeFileSync(path.join(outputAssetsDir, 'idyllium-web-core.js'), browserBundle(browserEntry), 'utf8');
fs.writeFileSync(path.join(outputDocsDir, 'index.html'), docsHtml(), 'utf8');

console.log(`Idyllium Web IDE built at ${path.relative(rootDir, outputWebDir)}`);

function browserBundle(entryFile) {
  const modules = collectModules(entryFile);
  const entries = [...modules.entries()].sort(([left], [right]) => left.localeCompare(right));
  const moduleFactories = entries.map(([id, file]) => (
    `${JSON.stringify(id)}: function(require, module, exports) {\n${fs.readFileSync(file, 'utf8')}\n}`
  ));
  const entryId = moduleId(entryFile);

  return `/* Generated by tools/build-web-ide.js */
(function (global) {
  'use strict';

  var modules = {
${moduleFactories.join(',\n')}
  };
  var cache = {};
  var builtins = createBuiltins();

  function load(id) {
    if (cache[id]) return cache[id].exports;
    if (!modules[id]) throw new Error('Module was not bundled: ' + id);
    var module = { exports: {} };
    cache[id] = module;
    modules[id](makeRequire(id), module, module.exports);
    return module.exports;
  }

  function makeRequire(from) {
    return function require(request) {
      if (builtins[request]) return builtins[request];
      if (request.charAt(0) !== '.') throw new Error('Unsupported browser require: ' + request);
      return load(resolveModuleId(from, request));
    };
  }

  function resolveModuleId(from, request) {
    var base = from.slice(0, from.lastIndexOf('/') + 1);
    var id = normalizePath(base + request);
    if (!/\\.js$/u.test(id)) id += '.js';
    return id;
  }

  function normalizePath(value) {
    var parts = value.replace(/\\\\/gu, '/').split('/');
    var result = [];
    for (var i = 0; i < parts.length; i++) {
      var part = parts[i];
      if (!part || part === '.') continue;
      if (part === '..') result.pop();
      else result.push(part);
    }
    return result.join('/');
  }

  function createBuiltins() {
    var pathBuiltin = {
      basename: function basename(value, ext) {
        var name = pathBuiltin.normalize(value).split('/').pop() || '';
        return ext && name.endsWith(ext) ? name.slice(0, -ext.length) : name;
      },
      dirname: function dirname(value) {
        var normalized = pathBuiltin.normalize(value);
        if (normalized === '/') return '/';
        var index = normalized.lastIndexOf('/');
        if (index <= 0) return normalized.charAt(0) === '/' ? '/' : '.';
        return normalized.slice(0, index);
      },
      isAbsolute: function isAbsolute(value) {
        return String(value).charAt(0) === '/';
      },
      join: function join() {
        return pathBuiltin.normalize(Array.prototype.join.call(arguments, '/'));
      },
      normalize: function normalize(value) {
        var raw = String(value).replace(/\\\\/gu, '/');
        var absolute = raw.charAt(0) === '/';
        var parts = raw.split('/');
        var result = [];
        for (var i = 0; i < parts.length; i++) {
          var part = parts[i];
          if (!part || part === '.') continue;
          if (part === '..') result.pop();
          else result.push(part);
        }
        return (absolute ? '/' : '') + result.join('/');
      },
      resolve: function resolve() {
        var value = '';
        for (var i = 0; i < arguments.length; i++) {
          var part = String(arguments[i]);
          value = part.charAt(0) === '/' ? part : value + '/' + part;
        }
        return pathBuiltin.normalize(value || '/');
      }
    };

    var fsBuiltin = {
      appendFileSync: function appendFileSync() { throw new Error('Node fs is not available in the browser'); },
      existsSync: function existsSync() { return false; },
      readFileSync: function readFileSync() { throw new Error('Node fs is not available in the browser'); },
      statSync: function statSync() { throw new Error('Node fs is not available in the browser'); },
      writeFileSync: function writeFileSync() { throw new Error('Node fs is not available in the browser'); }
    };

    return {
      buffer: { Buffer: BrowserBuffer },
      fs: fsBuiltin,
      path: pathBuiltin
    };
  }

  function BrowserBuffer(length) {
    return new Uint8Array(length);
  }

  BrowserBuffer.alloc = function alloc(length) {
    return enhanceBuffer(new Uint8Array(length));
  };

  BrowserBuffer.from = function from(value, encoding) {
    if (typeof value === 'string') {
      return enhanceBuffer(new TextEncoder().encode(value));
    }
    return enhanceBuffer(new Uint8Array(value));
  };

  function enhanceBuffer(bytes) {
    bytes.toString = function toString(encoding) {
      if (!encoding || String(encoding).toLowerCase() === 'utf8' || String(encoding).toLowerCase() === 'utf-8') {
        return new TextDecoder('utf-8').decode(bytes);
      }
      throw new Error('Unsupported browser buffer encoding: ' + encoding);
    };
    bytes.writeFloatBE = function writeFloatBE(value, offset) {
      new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength).setFloat32(offset, value, false);
    };
    bytes.writeDoubleBE = function writeDoubleBE(value, offset) {
      new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength).setFloat64(offset, value, false);
    };
    bytes.readFloatBE = function readFloatBE(offset) {
      return new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength).getFloat32(offset, false);
    };
    bytes.readDoubleBE = function readDoubleBE(offset) {
      return new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength).getFloat64(offset, false);
    };
    return bytes;
  }

  global.process = global.process || { cwd: function cwd() { return '/workspace'; } };
  global.Idyllium = load(${JSON.stringify(entryId)});
}(typeof window !== 'undefined' ? window : globalThis));
`;
}

function collectModules(entryFile) {
  const modules = new Map();
  const visit = (file) => {
    const id = moduleId(file);
    if (modules.has(id)) return;
    modules.set(id, file);

    const source = fs.readFileSync(file, 'utf8');
    for (const request of requireRequests(source)) {
      if (!request.startsWith('.')) continue;
      visit(resolveRequire(file, request));
    }
  };
  visit(entryFile);
  return modules;
}

function requireRequests(source) {
  const result = [];
  const pattern = /require\(["']([^"']+)["']\)/gu;
  let match = pattern.exec(source);
  while (match) {
    result.push(match[1]);
    match = pattern.exec(source);
  }
  return result;
}

function resolveRequire(fromFile, request) {
  const candidate = path.resolve(path.dirname(fromFile), request);
  const files = [
    candidate,
    `${candidate}.js`,
    path.join(candidate, 'index.js'),
  ];
  for (const file of files) {
    if (fs.existsSync(file)) return file;
  }
  throw new Error(`Cannot resolve ${request} from ${fromFile}`);
}

function moduleId(file) {
  return path.relative(distDir, file).split(path.sep).join('/');
}

function guiPreviewHtml() {
  const guiRenderer = require(path.join(rendererSourceDir, 'index.js'));
  return guiRenderer.renderGuiWebviewHtml({
    cssUri: 'gui-renderer/renderer.css',
    hostBootstrap: "window.IdylliumGuiHost = { postMessage: function(message) { parent.postMessage({ type: 'idylliumGuiEvent', message: message }, '*'); } };",
    nonce: 'idyllium-web',
    scriptUri: 'gui-renderer/renderer.js',
    state: { windows: [], canvases: [], modals: [], output: '' },
  });
}

function docsHtml() {
  const manifest = JSON.parse(fs.readFileSync(path.join(lessonSpecDir, 'manifest.json'), 'utf8'));
  const byLesson = new Map();
  for (const example of manifest.examples) {
    const key = `${example.section}/${example.lessonPath}`;
    const group = byLesson.get(key) || {
      section: example.section,
      title: example.lessonTitle,
      lessonPath: example.lessonPath,
      examples: [],
    };
    group.examples.push(example);
    byLesson.set(key, group);
  }

  const groups = [...byLesson.values()].sort((left, right) => (
    `${left.section}/${left.lessonPath}`.localeCompare(`${right.section}/${right.lessonPath}`)
  ));

  const nav = groups.map((group, index) => (
    `<a href="#lesson-${index}"><span>${escapeHtml(sectionTitle(group.section))}</span>${escapeHtml(group.title)}</a>`
  )).join('\n');

  const lessons = groups.map((group, index) => {
    const examples = group.examples.map((example) => {
      const code = fs.readFileSync(path.join(lessonSpecDir, example.codeFile), 'utf8');
      const badge = expectationTitle(example.expectation);
      return `<article class="example">
  <div class="example-meta">
    <span>${escapeHtml(example.id)}</span>
    <span>${escapeHtml(badge)}</span>
    <span>${escapeHtml(example.form)}</span>
  </div>
  <pre><code>${escapeHtml(code)}</code></pre>
</article>`;
    }).join('\n');

    return `<section id="lesson-${index}" class="lesson">
  <h2>${escapeHtml(group.title)}</h2>
  <p>${escapeHtml(sectionTitle(group.section))} · ${escapeHtml(group.lessonPath)}</p>
  ${examples}
</section>`;
  }).join('\n');

  return `<!doctype html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Документация Idyllium</title>
  <style>
    :root {
      color-scheme: dark;
      --bg: #151619;
      --panel: #202126;
      --panel-soft: #292b31;
      --border: #3a3d46;
      --text: #eef0f6;
      --muted: #a8adba;
      --accent: #54a1ff;
    }
    * { box-sizing: border-box; }
    body {
      margin: 0;
      display: grid;
      grid-template-columns: 300px 1fr;
      min-height: 100vh;
      background: var(--bg);
      color: var(--text);
      font: 14px/1.55 Inter, Segoe UI, Arial, sans-serif;
    }
    nav {
      position: sticky;
      top: 0;
      height: 100vh;
      overflow: auto;
      padding: 18px 12px;
      border-right: 1px solid var(--border);
      background: var(--panel);
    }
    nav h1 {
      margin: 0 0 14px;
      font-size: 20px;
    }
    nav a {
      display: block;
      padding: 8px 10px;
      border-radius: 6px;
      color: var(--text);
      text-decoration: none;
    }
    nav a:hover {
      background: var(--panel-soft);
    }
    nav a span {
      display: block;
      color: var(--muted);
      font-size: 11px;
      text-transform: uppercase;
    }
    main {
      min-width: 0;
      padding: 24px;
    }
    .intro,
    .lesson {
      max-width: 980px;
      margin: 0 auto 28px;
    }
    h2 {
      margin: 0 0 4px;
      font-size: 24px;
    }
    p {
      margin: 0 0 14px;
      color: var(--muted);
    }
    .example {
      margin: 14px 0;
      overflow: hidden;
      border: 1px solid var(--border);
      border-radius: 8px;
      background: var(--panel);
    }
    .example-meta {
      display: flex;
      gap: 8px;
      flex-wrap: wrap;
      padding: 8px 10px;
      border-bottom: 1px solid var(--border);
      color: var(--muted);
      font-size: 12px;
    }
    pre {
      margin: 0;
      overflow: auto;
      padding: 12px;
      background: #111214;
      color: #edf3ff;
      font: 13px/1.5 ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
    }
    @media (max-width: 900px) {
      body { grid-template-columns: 1fr; }
      nav {
        position: static;
        height: auto;
        max-height: 320px;
        border-right: 0;
        border-bottom: 1px solid var(--border);
      }
      main { padding: 16px; }
    }
  </style>
</head>
<body>
  <nav>
    <h1>Idyllium</h1>
    ${nav}
  </nav>
  <main>
    <section class="intro">
      <h2>Документация и примеры</h2>
      <p>Эта страница собрана из frozen spec: ${manifest.totalExamples} примеров. Ошибочные учебные примеры помечены отдельно.</p>
    </section>
    ${lessons}
  </main>
</body>
</html>`;
}

function sectionTitle(section) {
  if (section === 'cli') return 'Консоль';
  if (section === 'widgets') return 'GUI';
  if (section === 'oop') return 'ООП';
  return section;
}

function expectationTitle(expectation) {
  if (expectation === 'reject') return 'учебная ошибка';
  if (expectation === 'runtime-error') return 'ошибка выполнения';
  if (expectation === 'docs-only') return 'только документация';
  if (expectation === 'valid') return 'рабочий пример';
  return 'пример';
}

function escapeHtml(value) {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');
}
